# src/reporter/html_reporter.py
"""HTML取证报告生成（IF-DSS完全没有此功能）"""

import os
import json
from datetime import datetime
from jinja2 import Environment


REPORT_TEMPLATE = """<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>IPFS Forensics Report - {{ case_name }}</title>
    <style>
        body { font-family: Arial, sans-serif; margin: 40px; color: #333; }
        h1 { color: #2c3e50; border-bottom: 2px solid #3498db; padding-bottom: 10px; }
        h2 { color: #2980b9; margin-top: 30px; }
        table { border-collapse: collapse; width: 100%; margin: 20px 0; }
        th, td { border: 1px solid #ddd; padding: 8px; text-align: left; }
        th { background-color: #3498db; color: white; }
        tr:nth-child(even) { background-color: #f2f2f2; }
        .stats { background: #ecf0f1; padding: 15px; border-radius: 5px; margin: 10px 0; }
        .stats p { margin: 5px 0; }
        code { background: #eee; padding: 2px 6px; border-radius: 3px; }
        .footer { margin-top: 40px; color: #888; font-size: 0.9em; border-top: 1px solid #ddd; padding-top: 10px; }
    </style>
</head>
<body>
    <h1>IPFS Digital Forensics Report</h1>
    <p><strong>Case:</strong> {{ case_name }}</p>
    <p><strong>Generated:</strong> {{ timestamp }}</p>

    <h2>1. Identification</h2>
    <div class="stats">
        <p>Total URLs analyzed: {{ id_stats.total }}</p>
        <p>IPFS-related CIDs found: {{ id_stats.cids_found }}</p>
    </div>

    <h2>2. Collection</h2>
    <div class="stats">
        <p>CIDs tracked: {{ track_stats.total }}</p>
        <p>Providers found: {{ track_stats.found }}</p>
        <p>Not found: {{ track_stats.not_found }}</p>
    </div>

    {% if track_results %}
    <h3>IP Addresses Discovered</h3>
    <table>
        <tr><th>#</th><th>CID</th><th>IP Addresses</th></tr>
        {% for cid, data in track_results.items() %}
        <tr>
            <td>{{ loop.index }}</td>
            <td><code>{{ cid[:30] }}...</code></td>
            <td>{{ data.IP | join(', ') if data.IP else 'N/A' }}</td>
        </tr>
        {% endfor %}
    </table>
    {% endif %}

    {% if reassembly_stats %}
    <h2>3. Analysis - Block Reassembly</h2>
    <div class="stats">
        <p>Total blocks: {{ reassembly_stats.total_blocks }}</p>
        <p>Processed: {{ reassembly_stats.processed }}</p>
        <p>Trees (directories): {{ reassembly_stats.trees }}</p>
        <p>Lists (multi-block files): {{ reassembly_stats.lists }}</p>
        <p>Blobs (single-block files): {{ reassembly_stats.blobs }}</p>
        <p>Raw blocks: {{ reassembly_stats.raw_blocks }}</p>
        <p>Missing blocks: {{ reassembly_stats.missing_blocks }}</p>
        <p>Errors: {{ reassembly_stats.error_count }}</p>
    </div>
    {% endif %}

    {% if evidence_hashes %}
    <h2>4. Evidence Integrity</h2>
    <table>
        <tr><th>#</th><th>File</th><th>SHA-256</th><th>Size</th><th>Collected</th></tr>
        {% for entry in evidence_hashes %}
        <tr>
            <td>{{ loop.index }}</td>
            <td><code>{{ entry.file_short }}</code></td>
            <td><code>{{ entry.sha256[:20] }}...</code></td>
            <td>{{ entry.size }} bytes</td>
            <td>{{ entry.timestamp }}</td>
        </tr>
        {% endfor %}
    </table>
    {% endif %}

    <h2>5. Limitations</h2>
    <p>{{ limitations }}</p>

    <div class="footer">
        <p>Generated by IPFS-Forensics-System | Based on IF-DSS (Son et al., DFRWS 2023)</p>
    </div>
</body>
</html>"""


def generate_report(case_name, output_dir, **kwargs):
    """生成HTML取证报告"""

    env = Environment()
    template = env.from_string(REPORT_TEMPLATE)

    # 加载证据哈希
    hash_file = os.path.join(output_dir, "evidence_hashes.json")
    hashes = []
    if os.path.exists(hash_file):
        with open(hash_file, 'r') as f:
            hashes = json.load(f)
        for entry in hashes:
            entry["file_short"] = os.path.basename(entry.get("file", ""))

    html = template.render(
        case_name=case_name,
        timestamp=datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
        evidence_hashes=hashes,
        limitations="This system targets IPFS/Filecoin only. "
                    "Nodes behind NAT may not be reachable. "
                    "Encrypted blocks (Storj/Sia) cannot be reassembled.",
        **kwargs
    )

    report_path = os.path.join(output_dir, f"report_{case_name}.html")
    with open(report_path, 'w', encoding='utf-8') as f:
        f.write(html)

    print(f"[OK] Report saved to {report_path}")
    return report_path